Repository camptocamp/helm-application, pull requests merged in 2022-12, with the labels that each got.

#77 Configure Mend Bolt
  .editorconfig
  .whitesource
Labels: chore

#78 Configure Renovate to run monthly
  .github/renovate.json5
Labels: chore

#79 Configure Renovate for kubernetes
  .github/renovate.json5
Labels: chore

#80 GEO-6100: add logic for range over services
  Chart.yaml
  templates/deployment.yaml
  templates/ingress.yaml
  templates/pdb.yaml
  templates/service.yaml
  tests/expected.yaml
  tests/mapserver-expected.yaml
  tests/values.yaml
  values.yaml
Labels: enhancement

#81 Update to helm-common 0.4.1
  Chart.yaml
Labels: dependencies
